version: 1.0.3
description: UPF2 local configuration

pfcp:
  addr: upf2.free5gc.org
  nodeID: upf2.free5gc.org
  retransTimeout: 1s
  maxRetrans: 3

gtpu:
  forwarder: gtp5g
  ifList:
    - addr: upf2.free5gc.org
      type: N3

dnnList:
  - dnn: internet2
    cidr: 10.70.0.0/16

logger:
  enable: true
  level: info
  reportCaller: false

